# -*- coding: utf-8 -*-
"""Random number generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_Y4EF7KeaKto3PwTW9jU-cDNQO1LP-c
"""

import random

def generateRandomNumber(): #  Function for generate random number
    randomNumber = random.randint(1,100)
    return randomNumber
def askuserForNumber (message = "Guess the number : "):# Function to ask user to guess what the number 
    userNumber = int(input(message))
    return userNumber
def checkUserNumber (userNumber , randomNumber):# Function checking the user number to see basically what did is 
    if userNumber > randomNumber :
        return "Too high"
    elif userNumber<randomNumber:
        return "Too Low"
    else : 
        return " Congratulations ! "

def main():# Main Function 
    print("Random Number Guessing")
    UserCongratulated =False # When the game start the user has been Conguralated
    LetsStart = True
    
    while UserCongratulated or LetsStart: # Any one of two variable is true will excuted While loop
        UserNumberOfGusses =0 # It keeps count of the number of guesses that user makes
        randomNumber = generateRandomNumber()
        userNumber = askuserForNumber() # Ask the user again the guess number and types of the number
        UserNumberOfGusses = UserNumberOfGusses + 1 
        message = checkUserNumber (userNumber , randomNumber)
       
        
        while message != " Congratulations ! " : # If the the meessage keep High or Low will ask te user keep on guessing
            print(message) # Print message if high or low
            userNumber = askuserForNumber ("Try Again: ")# Ask the user again the guess number with message "Try again"
            UserNumberOfGusses = UserNumberOfGusses + 1 # If the guesses number is wrong will be add one and exuted while loop untile get correct guess the number
            message = checkUserNumber (userNumber , randomNumber) # If the userName = randomNumber it will  return Congratulations
        print() 
        print(message, "it took you" , UserNumberOfGusses,\
               "attempt to guess correctly\n" )  # If the Number of guess equal true  it will print the message 
        UserCongratulated =True # If UserCongratulated equal True it will excuted program but if the value is False will not excuted program
main()

